#!/bin/bash
# Quick session primer for Claude Code

echo "🎮 WEDDING GAME PROJECT PRIMER 🎮"
echo "=================================="
echo ""
echo "📋 CORE APPROACH:"
echo "  • DISCUSSION-DRIVEN project - conversation first, code second"
echo "  • Always ask design questions before implementing"
echo "  • Present 2-3 options for user choice"
echo "  • Get approval before coding"
echo ""
echo "🎯 GAME IDENTITY:"
echo "  • NOT a wedding game - chaotic hub-based RPG"
echo "  • South Park + Celebrity Death Match + Pokemon style"
echo "  • Intentionally frustrating and chaotic"
echo "  • Dark humor, over-the-top violence"
echo ""
echo "🚨 EMERGENCY STOP: 'Stop - discuss first'"
echo ""
echo "📚 KEY FILES:"
echo "  • CLAUDE.md - Full collaboration instructions"
echo "  • docs/revised_game_design_context.md - Game identity"
echo "  • docs/wedding_game_characters_script.md - Character details"
echo ""
echo "Ready for collaborative game development!"