#!/bin/bash
# Complete session primer for Claude Code - Wedding Game Project

echo "🎮 WEDDING GAME PROJECT PRIMER 🎮"
echo "=================================="
echo ""
echo "📋 CORE APPROACH:"
echo "  • DISCUSSION-DRIVEN project - conversation first, code second"
echo "  • Always ask design questions before implementing"
echo "  • Present 2-3 options for user choice"
echo "  • Get approval before coding"
echo "  • Reference CLAUDE.md for full collaboration protocol"
echo ""
echo "🎯 GAME IDENTITY:"
echo "  • NOT a wedding game - chaotic hub-based RPG"
echo "  • South Park + Celebrity Death Match + Pokemon aesthetic"
echo "  • Intentionally frustrating and chaotic gameplay"
echo "  • Dark humor, over-the-top violence, absurdist adventure"
echo "  • Hub world (Pallet Town style) connects mismatched mini-games"
echo ""
echo "🏗️ ARCHITECTURE STATUS:"
echo "  • Godot 4.4 engine with autoload managers"
echo "  • Hub world foundation COMPLETE (Main.tscn, Player, LevelEntrance)"
echo "  • GameManager, SpriteManager, AudioManager autoloads READY"
echo "  • TaskMaster integration with 6 discussion tasks ACTIVE"
echo "  • DialogueManager addon for story/character interactions"
echo ""
echo "📋 TASKMASTER TASKS (Current Phase: discussion_foundation):"
echo "  HIGH PRIORITY:"
echo "    1. hub_visual_style - Visual aesthetic discussion"
echo "    2. level_entrance_ideas - Creative mini-game access"
echo "    3. character_hub_behaviors - Glen chaos vs Quinn management"
echo "  MEDIUM PRIORITY:"
echo "    4. dialogue_style_integration - Dark humor + DialogueManager"
echo "    5. hub_world_layout - Single screen vs explorable area"
echo "    6. first_minigame_prototype - Choose mechanics to develop"
echo ""
echo "🤖 MCP INTEGRATION:"
echo "  • 18 overflow tools available (memory, sequential thinking)"
echo "  • Memory system for storing design decisions"
echo "  • Sequential thinking for complex problem solving"
echo "  • Task-to-tool mapping documented"
echo ""
echo "🚨 EMERGENCY STOP: 'Stop - discuss first'"
echo ""
echo "📚 KEY DOCUMENTATION:"
echo "  • CLAUDE.md - Collaboration instructions"
echo "  • docs/revised_game_design_context.md - Game identity"
echo "  • docs/master-workflow.md - Development workflow"
echo "  • docs/architecture-decisions.md - Technical decisions"
echo "  • docs/wedding_game_characters_script.md - Character details"
echo "  • docs/taskmaster-mcp-integration-analysis.md - MCP setup"
echo ""
echo "✅ SESSION SETUP COMMANDS:"
echo "  • Check TaskMaster: ./scripts/dev-session-manager.sh status"
echo "  • View MCP tools: python3 scripts/aggregate_tools.py --test"
echo "  • Git status: git status"
echo "  • Current tasks: Check .taskmaster/tasks.json"
echo ""
echo "🎯 READY FOR COLLABORATIVE GAME DEVELOPMENT!"
echo "    Start with TaskMaster discussion tasks - which would you like to tackle?"